### ISSUE TITLE
[質問]Constではなくreadonlyを利用した理由を説明してください。

### ISSUE THREAD

**Issue by honobonoK** [ShinF291/PracticeUnity#6]
https://github.com/ShinF291/PracticeUnity/blob/f0f320b80e5020b5f0f53a5b2cac8eacebcddce9/Kanji/Assets/AppPackages/Ra-MEN/Guzai/Scripts/View/GuzaiView.cs#L20-L21

合わせて勉強会の復習ですがConstとreadonlyの違いを説明してください

**Comment by ShinF291** [comment]
このあたりあまり意識せず使っており、読み取り専用の定数であるという意図で使っておりました。

constはフィールドで宣言するもので、readonlyはコンストラクタでなら初期化できるやつです。

今回の場合は最初の宣言以外で値変える予定ないのでconstが適切かと思います。

**Comment by honobonoK** [comment]
挙動的に何が違うか説明お願いします。
調べた上で自分の言葉で記述できればOKです。
`constはフィールドで宣言するもので、readonlyはコンストラクタでなら初期化できるやつです。`
↑ただしく理解できているか判断できませんでした。

**Comment by ShinF291** [comment]
const はコンパイル時に値が決定する定数。そのためフィールドで初期化しなければなりません。
しかしコンパイル時点で決定してしまうので、newなどコンストラクタで計算された値は代入できません。
ビルド時点で値が決まっているためアプリ容量は少し重く、処理は軽いです。

readonly は実行時に値が決まる定数です。そのためnewを用いたコンストラクタで初期化可能です。
しかし変数と同じく処理が重く、アプリ容量は軽いです。
